name: stock_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  get: 4.6.6
  dio: ^5.4.0
  warp: ^0.1.0
  get_cli: ^1.8.4
  get_storage: ^2.1.1
  flutter_svg: ^2.0.9
  file_picker: ^5.3.1
  image_picker: ^1.0.5
  device_info_plus: ^9.1.1
  permission_handler: ^11.1.0
  emoji_picker_flutter: ^1.6.3
  cached_network_image: ^3.3.0


dev_dependencies:
  build_runner: ^2.4.7
  flutter_lints: ^3.0.1
  flutter_launcher_icons: any
  flutter_native_splash: ^2.3.8
  change_app_package_name: ^1.1.0

flutter_gen:
  output: lib/app/gen/
  line_length: 80
  assets:
    outputs:
      style: camel-case

  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/

